
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace NewSolutionDialog {
    using System;
    using Terminal.Gui;
    
    
    public partial class NewSolutionDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.TextField tfSearchBox;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.Label lblTemplateName;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label lblTemplateAuthor;
        
        private Terminal.Gui.ScrollView scrollView;
        
        private Terminal.Gui.ListView lvAvalableTemplates;
        
        private Terminal.Gui.FrameView frameView2;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.TextField tfSolutionDir;
        
        private Terminal.Gui.Button btnDir;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField tfSolutionName;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.TextField tfProjectName;
        
        private Terminal.Gui.Label label6;
        
        private Terminal.Gui.ComboBox cbLanguage;
        
        private Terminal.Gui.Label label7;
        
        private Terminal.Gui.ListView lvProjectStructure;
        
        private Terminal.Gui.Button btnCreate;
        
        private Terminal.Gui.Button btnCancle;
        
        private void InitializeComponent() {
            this.btnCancle = new Terminal.Gui.Button();
            this.btnCreate = new Terminal.Gui.Button();
            this.lvProjectStructure = new Terminal.Gui.ListView();
            this.label7 = new Terminal.Gui.Label();
            this.cbLanguage = new Terminal.Gui.ComboBox();
            this.label6 = new Terminal.Gui.Label();
            this.tfProjectName = new Terminal.Gui.TextField();
            this.label4 = new Terminal.Gui.Label();
            this.tfSolutionName = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.btnDir = new Terminal.Gui.Button();
            this.tfSolutionDir = new Terminal.Gui.TextField();
            this.label5 = new Terminal.Gui.Label();
            this.frameView2 = new Terminal.Gui.FrameView();
            this.lvAvalableTemplates = new Terminal.Gui.ListView();
            this.scrollView = new Terminal.Gui.ScrollView();
            this.lblTemplateAuthor = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.lblTemplateName = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.frameView = new Terminal.Gui.FrameView();
            this.tfSearchBox = new Terminal.Gui.TextField();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.tfSearchBox.Width = 32;
            this.tfSearchBox.Height = 1;
            this.tfSearchBox.X = 1;
            this.tfSearchBox.Y = 0;
            this.tfSearchBox.ColorScheme = this.tgDefault;
            this.tfSearchBox.Secret = false;
            this.tfSearchBox.Data = "tfSearchBox";
            this.tfSearchBox.Text = "Search...";
            this.tfSearchBox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tfSearchBox);
            this.frameView.Width = Dim.Fill(1);
            this.frameView.Height = 6;
            this.frameView.X = 35;
            this.frameView.Y = 0;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Template Info";
            this.Add(this.frameView);
            this.label3.Width = 15;
            this.label3.Height = 1;
            this.label3.X = 2;
            this.label3.Y = 1;
            this.label3.Data = "label3";
            this.label3.Text = "Template Name :";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.label3);
            this.lblTemplateName.Width = Dim.Fill(4);
            this.lblTemplateName.Height = 1;
            this.lblTemplateName.X = 19;
            this.lblTemplateName.Y = 1;
            this.lblTemplateName.ColorScheme = this.greyOnBlack;
            this.lblTemplateName.Data = "lblTemplateName";
            this.lblTemplateName.Text = "Template Full Name here";
            this.lblTemplateName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.lblTemplateName);
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 9;
            this.label.Y = 3;
            this.label.Data = "label";
            this.label.Text = "Author :";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.label);
            this.lblTemplateAuthor.Width = Dim.Fill(4);
            this.lblTemplateAuthor.Height = 1;
            this.lblTemplateAuthor.X = 19;
            this.lblTemplateAuthor.Y = 3;
            this.lblTemplateAuthor.ColorScheme = this.greyOnBlack;
            this.lblTemplateAuthor.Data = "lblTemplateAuthor";
            this.lblTemplateAuthor.Text = "Author Name Here";
            this.lblTemplateAuthor.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Add(this.lblTemplateAuthor);
            this.scrollView.Width = 32;
            this.scrollView.Height = 27;
            this.scrollView.X = 1;
            this.scrollView.Y = 2;
            this.scrollView.ContentSize = new Size(31,24);
            this.scrollView.Data = "scrollView";
            this.scrollView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scrollView);
            this.lvAvalableTemplates.Width = Dim.Fill(0);
            this.lvAvalableTemplates.Height = Dim.Fill(0);
            this.lvAvalableTemplates.X = 0;
            this.lvAvalableTemplates.Y = 1;
            this.lvAvalableTemplates.ColorScheme = this.tgDefault;
            this.lvAvalableTemplates.Data = "lvAvalableTemplates";
            this.lvAvalableTemplates.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lvAvalableTemplates.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.scrollView.Add(this.lvAvalableTemplates);
            this.frameView2.Width = Dim.Fill(1);
            this.frameView2.Height = Dim.Fill(5);
            this.frameView2.X = 35;
            this.frameView2.Y = 6;
            this.frameView2.Data = "frameView2";
            this.frameView2.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView2.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView2.Border.Effect3D = false;
            this.frameView2.Border.Effect3DBrush = null;
            this.frameView2.Border.DrawMarginFrame = true;
            this.frameView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Title = "Solution Setup";
            this.Add(this.frameView2);
            this.label5.Width = 4;
            this.label5.Height = 1;
            this.label5.X = 1;
            this.label5.Y = 1;
            this.label5.Data = "label5";
            this.label5.Text = "Solution Directory :";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.label5);
            this.tfSolutionDir.Width = Dim.Percent(50f);
            this.tfSolutionDir.Height = 1;
            this.tfSolutionDir.X = Pos.Left(label5) + 21;
            this.tfSolutionDir.Y = 1;
            this.tfSolutionDir.ColorScheme = this.tgDefault;
            this.tfSolutionDir.Secret = false;
            this.tfSolutionDir.Data = "tfSolutionDir";
            this.tfSolutionDir.Text = "/home/user/code/projName";
            this.tfSolutionDir.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.tfSolutionDir);
            this.btnDir.Width = 7;
            this.btnDir.Height = 1;
            this.btnDir.X = Pos.Right(tfSolutionDir) + 1;
            this.btnDir.Y = 1;
            this.btnDir.Data = "btnDir";
            this.btnDir.Text = "DIR";
            this.btnDir.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnDir.IsDefault = false;
            this.frameView2.Add(this.btnDir);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 6;
            this.label2.Y = 3;
            this.label2.Data = "label2";
            this.label2.Text = "Solution Name :";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.label2);
            this.tfSolutionName.Width = Dim.Fill(4);
            this.tfSolutionName.Height = 1;
            this.tfSolutionName.X = 22;
            this.tfSolutionName.Y = 3;
            this.tfSolutionName.ColorScheme = this.tgDefault;
            this.tfSolutionName.Secret = false;
            this.tfSolutionName.Data = "tfSolutionName";
            this.tfSolutionName.Text = "Solution Name";
            this.tfSolutionName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.tfSolutionName);
            this.label4.Width = 14;
            this.label4.Height = 1;
            this.label4.X = 7;
            this.label4.Y = 5;
            this.label4.Data = "label4";
            this.label4.Text = "Project Name :";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.label4);
            this.tfProjectName.Width = Dim.Fill(4);
            this.tfProjectName.Height = 1;
            this.tfProjectName.X = 22;
            this.tfProjectName.Y = 5;
            this.tfProjectName.ColorScheme = this.tgDefault;
            this.tfProjectName.Secret = false;
            this.tfProjectName.Data = "tfProjectName";
            this.tfProjectName.Text = "Project Name";
            this.tfProjectName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.tfProjectName);
            this.label6.Width = 4;
            this.label6.Height = 1;
            this.label6.X = 11;
            this.label6.Y = 7;
            this.label6.Data = "label6";
            this.label6.Text = "Language :";
            this.label6.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.label6);
            this.cbLanguage.Width = 8;
            this.cbLanguage.Height = 4;
            this.cbLanguage.X = 22;
            this.cbLanguage.Y = 7;
            this.cbLanguage.ColorScheme = this.tgDefault;
            this.cbLanguage.Data = "cbLanguage";
            this.cbLanguage.Text = "";
            this.cbLanguage.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.cbLanguage);
            this.label7.Width = 14;
            this.label7.Height = 1;
            this.label7.X = 6;
            this.label7.Y = 9;
            this.label7.Data = "label7";
            this.label7.Text = "Projected File Structure :";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Add(this.label7);
            this.lvProjectStructure.Width = Dim.Fill(0);
            this.lvProjectStructure.Height = 4;
            this.lvProjectStructure.X = 6;
            this.lvProjectStructure.Y = 11;
            this.lvProjectStructure.Data = "lvProjectStructure";
            this.lvProjectStructure.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.lvProjectStructure.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.frameView2.Add(this.lvProjectStructure);
            this.btnCreate.Width = 10;
            this.btnCreate.Height = 1;
            this.btnCreate.X = Pos.Left(lvProjectStructure) + 1;
            this.btnCreate.Y = Pos.Bottom(lvProjectStructure) + 1;
            this.btnCreate.ColorScheme = this.greenOnBlack;
            this.btnCreate.Data = "btnCreate";
            this.btnCreate.Text = "Create";
            this.btnCreate.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCreate.IsDefault = false;
            this.frameView2.Add(this.btnCreate);
            this.btnCancle.Width = 10;
            this.btnCancle.Height = 1;
            this.btnCancle.X = Pos.Right(btnCreate);
            this.btnCancle.Y = Pos.Bottom(lvProjectStructure) + 1;
            this.btnCancle.ColorScheme = this.redOnBlack;
            this.btnCancle.Data = "btnCancle";
            this.btnCancle.Text = "Cancle";
            this.btnCancle.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancle.IsDefault = false;
            this.frameView2.Add(this.btnCancle);
        }
    }
}
